version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7
   
    environment:
      GO111MODULE: "on"
    
    working_directory: /go/src/github.com/deislabs/smi-sdk-go
    
    steps:
      - checkout

      - run: 
          name: Install modules
          command: go get ./... 
      
      - run: 
          name: Build installer
          command: go build ./cmd/installer/installer.go

      - run: 
          name: Execute code generation
          command: cd ./hack/update-codegen.sh

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
