version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/deislabs/smi-sdk-go
    steps:
      - checkout
      - run: make bootstrap
      - run: make test
